python exps/forecast/train/train_forecast.py \
  --mode per_city \
  --city-electricity-csv "Ottawa=data/ieso_hourly/ieso_residential_Ottawa.csv.gz" \
  --city-meteo-csv      "Ottawa=data/era5/ottawa_era5_timeseries.csv.gz" \
  --features "t2m_degC, tp_mm, net_radiation_Wm2" \
  --history 168 --horizon 24 \
  --epochs 500 --batch-size 128 \
  --model patchtst \
  --model-module utils.forecast.PatchTST \
  --model-class PatchTSTModel \
  --model-kwarg 'd_model=128' --model-kwarg 'context_length=168' \
  --exp-name percity_ottawa_h168_h24_patchtst
