python exps/forecast/train/train_forecast.py \
  --mode multi_city \
  --city-electricity-csv "Ottawa=data/ieso_hourly/ieso_residential_Ottawa.csv.gz" --city-electricity-csv "Toronto=data/ieso_hourly/ieso_residential_Toronto.csv.gz" --city-electricity-csv "Hamilton=data/ieso_hourly/ieso_residential_Hamilton.csv.gz" \
  --city-meteo-csv      "Ottawa=data/era5/ottawa_era5_timeseries.csv.gz" --city-meteo-csv      "Toronto=data/era5/toronto_era5_timeseries.csv.gz" --city-meteo-csv      "Hamilton=data/era5/hamilton_era5_timeseries.csv.gz" \
  --features "t2m_degC, tp_mm, net_radiation_Wm2" \
  --history 168 --horizon 24 \
  --epochs 500 --batch-size 128 \
  --model tcn \
  --model-module utils.forecast.TCN \
  --model-class TCNModel \
  --model-kwarg 'hidden_channels=128' --model-kwarg 'levels=6' --model-kwarg 'kernel_size=3' --model-kwarg 'num_targets=1' \
  --exp-name multicity_h168_h24_tcn
